/**
 * Blog Content Registry
 *
 * Central index of all blog posts.
 * Auto-generated by migration script.
 */
import type { BlogPost } from "@/lib/blog/types";
import { initializeRegistry } from "@/lib/blog/registry";

// SEO POSTS
import * as local_seo_checklist_2026 from "./seo/local-seo-checklist-2026";
import * as seo_checklist_small_business from "./seo/seo-checklist-small-business";
import * as local_seo_guide_small_business from "./seo/local-seo-guide-small-business";
import * as ecommerce_seo_complete_guide from "./seo/ecommerce-seo-complete-guide";
import * as seo_checklist_2026 from "./seo/seo-checklist-2026";
// REMOVED: local-seo-guide.tsx - Redirected to local-seo-guide-small-business (keyword cannibalization fix)
import * as digital_marketing_tools_comparison from "./seo/digital-marketing-tools-comparison";
import * as technical_seo_audit from "./seo/technical-seo-audit";
import * as seo_for_small_business from "./seo/seo-for-small-business";
import * as keyword_research_guide from "./seo/keyword-research-guide";
import * as link_building_strategies from "./seo/link-building-strategies";
import * as seo_content_writing from "./seo/seo-content-writing";
import * as google_search_carousels_beta_complete_seo_guide from "./seo/google-search-carousels-beta-complete-seo-guide";
import * as how_to_implement_google_search_carousels_step_by_step from "./seo/how-to-implement-google-search-carousels-step-by-step";
import * as google_search_appearance_optimization_guide from "./seo/google-search-appearance-optimization-guide";
import * as structured_data_implementation_guide from "./seo/structured-data-implementation-guide";
import * as seo_starter_guide_2026_what_google_actually_wants from "./seo/seo-starter-guide-2026-what-google-actually-wants";
import * as seo_myths_debunked_2026_what_actually_works from "./seo/seo-myths-debunked-2026-what-actually-works";
import * as google_december_2025_core_update_what_changed from "./seo/google-december-2025-core-update-what-changed";
import * as how_to_recover_december_2025_core_update from "./seo/how-to-recover-december-2025-core-update";
import * as eeat_complete_guide_2026 from "./seo/eeat-complete-guide-2026";
import * as image_video_seo_optimization_complete_guide_2026 from "./seo/image-video-seo-optimization-complete-guide-2026";
import * as technical_seo_checklist_2026_complete_guide from "./seo/technical-seo-checklist-2026-complete-guide";
import * as content_quality_seo_strategies_2026 from "./seo/content-quality-seo-strategies-2026";
import * as google_search_essentials_complete_guide_2026 from "./seo/google-search-essentials-complete-guide-2026";
import * as avoiding_google_penalties_spam_policy_compliance_guide from "./seo/avoiding-google-penalties-spam-policy-compliance-guide";
import * as advanced_seo_best_practices_beyond_essentials_2026 from "./seo/advanced-seo-best-practices-beyond-essentials-2026";
import * as featured_snippets_rich_results_implementation_guide from "./seo/featured-snippets-rich-results-implementation-guide";
import * as technical_seo_playbook_2026 from "./seo/technical-seo-playbook-2026";
import * as why_google_stopped_trusting_your_website from "./seo/why-google-stopped-trusting-your-website";
import * as winning_ai_search_era_executive_guide from "./seo/winning-ai-search-era-executive-guide";
import * as google_algorithm_updates_2025_complete_guide from "./seo/google-algorithm-updates-2025-complete-guide";
import * as what_is_geo_optimization from "./seo/what-is-geo-optimization";
import * as geo_vs_traditional_seo from "./seo/geo-vs-traditional-seo";
import * as how_to_optimize_for_ai_search from "./seo/how-to-optimize-for-ai-search";
import * as ai_citations_optimization_guide from "./seo/ai-citations-optimization-guide";
import * as ranking_number_1_in_google_2026_ai_overviews from "./seo/ranking-number-1-in-google-2026-ai-overviews";
import * as best_free_seo_tools_2026 from "./seo/best-free-seo-tools-2026";
import * as free_ahrefs_semrush_alternative from "./seo/free-ahrefs-semrush-alternative";
import * as how_to_do_seo_audit from "./seo/how-to-do-seo-audit";
import * as how_to_write_meta_tags from "./seo/how-to-write-meta-tags";
import * as how_to_add_schema_markup from "./seo/how-to-add-schema-markup";
import * as how_to_improve_core_web_vitals from "./seo/how-to-improve-core-web-vitals";

// SEO CONTENT CLUSTER
import * as programmatic_seo_guide from "./seo/programmatic-seo-guide";
import * as topical_authority_building_guide from "./seo/topical-authority-building-guide";
import * as internal_linking_strategy_guide from "./seo/internal-linking-strategy-guide";
import * as seo_for_saas_companies from "./seo/seo-for-saas-companies";
import * as google_search_console_complete_guide from "./seo/google-search-console-complete-guide";
import * as local_seo_google_business_profile_2026 from "./seo/local-seo-google-business-profile-2026";
import * as google_march_2026_core_update from "./seo/google-march-2026-core-update";
import * as ai_overviews_seo_impact from "./seo/ai-overviews-seo-impact";
import * as seo_for_ai_era from "./seo/seo-for-ai-era";
import * as seo_for_local_businesses_2026 from "./seo/seo-for-local-businesses-2026";
import * as geo_content_playbook_data_driven_ai_citations from "./seo/geo-content-playbook-data-driven-ai-citations";
import * as aeo_technical_stack_robots_txt_llms_txt_ai_crawlers from "./seo/aeo-technical-stack-robots-txt-llms-txt-ai-crawlers";

// ============================================================================
// ALL POSTS
// ============================================================================
const allPosts: BlogPost[] = [
  { ...local_seo_checklist_2026.metadata, Content: local_seo_checklist_2026.Content },
  { ...seo_checklist_small_business.metadata, Content: seo_checklist_small_business.Content },
  { ...local_seo_guide_small_business.metadata, Content: local_seo_guide_small_business.Content },
  { ...ecommerce_seo_complete_guide.metadata, Content: ecommerce_seo_complete_guide.Content },
  { ...seo_checklist_2026.metadata, Content: seo_checklist_2026.Content },
  { ...digital_marketing_tools_comparison.metadata, Content: digital_marketing_tools_comparison.Content },
  { ...technical_seo_audit.metadata, Content: technical_seo_audit.Content },
  { ...seo_for_small_business.metadata, Content: seo_for_small_business.Content },
  { ...keyword_research_guide.metadata, Content: keyword_research_guide.Content },
  { ...link_building_strategies.metadata, Content: link_building_strategies.Content },
  { ...seo_content_writing.metadata, Content: seo_content_writing.Content },
  { ...google_search_carousels_beta_complete_seo_guide.metadata, Content: google_search_carousels_beta_complete_seo_guide.Content },
  { ...how_to_implement_google_search_carousels_step_by_step.metadata, Content: how_to_implement_google_search_carousels_step_by_step.Content },
  { ...google_search_appearance_optimization_guide.metadata, Content: google_search_appearance_optimization_guide.Content },
  { ...structured_data_implementation_guide.metadata, Content: structured_data_implementation_guide.Content },
  { ...seo_starter_guide_2026_what_google_actually_wants.metadata, Content: seo_starter_guide_2026_what_google_actually_wants.Content },
  { ...seo_myths_debunked_2026_what_actually_works.metadata, Content: seo_myths_debunked_2026_what_actually_works.Content },
  { ...google_december_2025_core_update_what_changed.metadata, Content: google_december_2025_core_update_what_changed.Content },
  { ...how_to_recover_december_2025_core_update.metadata, Content: how_to_recover_december_2025_core_update.Content },
  { ...eeat_complete_guide_2026.metadata, Content: eeat_complete_guide_2026.Content },
  { ...image_video_seo_optimization_complete_guide_2026.metadata, Content: image_video_seo_optimization_complete_guide_2026.Content },
  { ...technical_seo_checklist_2026_complete_guide.metadata, Content: technical_seo_checklist_2026_complete_guide.Content },
  { ...content_quality_seo_strategies_2026.metadata, Content: content_quality_seo_strategies_2026.Content },
  { ...google_search_essentials_complete_guide_2026.metadata, Content: google_search_essentials_complete_guide_2026.Content },
  { ...avoiding_google_penalties_spam_policy_compliance_guide.metadata, Content: avoiding_google_penalties_spam_policy_compliance_guide.Content },
  { ...advanced_seo_best_practices_beyond_essentials_2026.metadata, Content: advanced_seo_best_practices_beyond_essentials_2026.Content },
  { ...featured_snippets_rich_results_implementation_guide.metadata, Content: featured_snippets_rich_results_implementation_guide.Content },
  { ...technical_seo_playbook_2026.metadata, Content: technical_seo_playbook_2026.Content },
  { ...why_google_stopped_trusting_your_website.metadata, Content: why_google_stopped_trusting_your_website.Content },
  { ...winning_ai_search_era_executive_guide.metadata, Content: winning_ai_search_era_executive_guide.Content },
  { ...google_algorithm_updates_2025_complete_guide.metadata, Content: google_algorithm_updates_2025_complete_guide.Content },
  { ...what_is_geo_optimization.metadata, Content: what_is_geo_optimization.Content },
  { ...geo_vs_traditional_seo.metadata, Content: geo_vs_traditional_seo.Content },
  { ...how_to_optimize_for_ai_search.metadata, Content: how_to_optimize_for_ai_search.Content },
  { ...ai_citations_optimization_guide.metadata, Content: ai_citations_optimization_guide.Content },
  { ...ranking_number_1_in_google_2026_ai_overviews.metadata, Content: ranking_number_1_in_google_2026_ai_overviews.Content },
  { ...best_free_seo_tools_2026.metadata, Content: best_free_seo_tools_2026.Content },
  { ...free_ahrefs_semrush_alternative.metadata, Content: free_ahrefs_semrush_alternative.Content },
  { ...how_to_do_seo_audit.metadata, Content: how_to_do_seo_audit.Content },
  { ...how_to_write_meta_tags.metadata, Content: how_to_write_meta_tags.Content },
  { ...how_to_add_schema_markup.metadata, Content: how_to_add_schema_markup.Content },
  { ...how_to_improve_core_web_vitals.metadata, Content: how_to_improve_core_web_vitals.Content },
  // SEO CONTENT CLUSTER
  { ...programmatic_seo_guide.metadata, Content: programmatic_seo_guide.Content },
  { ...topical_authority_building_guide.metadata, Content: topical_authority_building_guide.Content },
  { ...internal_linking_strategy_guide.metadata, Content: internal_linking_strategy_guide.Content },
  { ...seo_for_saas_companies.metadata, Content: seo_for_saas_companies.Content },
  { ...google_search_console_complete_guide.metadata, Content: google_search_console_complete_guide.Content },
  { ...local_seo_google_business_profile_2026.metadata, Content: local_seo_google_business_profile_2026.Content },
  { ...google_march_2026_core_update.metadata, Content: google_march_2026_core_update.Content },
  { ...ai_overviews_seo_impact.metadata, Content: ai_overviews_seo_impact.Content },
  { ...seo_for_ai_era.metadata, Content: seo_for_ai_era.Content },
  { ...seo_for_local_businesses_2026.metadata, Content: seo_for_local_businesses_2026.Content },
  // GEO + AEO CLUSTER
  { ...geo_content_playbook_data_driven_ai_citations.metadata, Content: geo_content_playbook_data_driven_ai_citations.Content },
  { ...aeo_technical_stack_robots_txt_llms_txt_ai_crawlers.metadata, Content: aeo_technical_stack_robots_txt_llms_txt_ai_crawlers.Content },
];

// Initialize the registry
initializeRegistry(allPosts);

export { allPosts };
